### ISSUE TITLE
Problem with Summing-up Reputations

### ISSUE THREAD

**Issue by neilmarion** [twitter/activerecord-reputation-system#51]
I have this in my User model

  has_many :evaluations, class_name: "RSEvaluation", as: :source
  has_many :questions
  has_many :answers

  has_reputation :karma,
      :source => [
          { :reputation => :questioning_skill },
          { :reputation => :answering_skill } ] 

  has_reputation :questioning_skill,
      :source => { :reputation => :votes, :of => :questions }

  has_reputation :answering_skill,
      :source => { :reputation => :votes, :of => :answers }

But whenever I user.reputation_for(:karma) I always get 0.0.
No problem with user.reputation_for(:questioning_skill) because I get the correct value.

**Comment by ssoulless** [comment]
Same issue, the url you gave is not working, please tell me how did you solve it, it seems that the issue is when you use `class_name` option in the relationship declaration

https://github.com/twitter/activerecord-reputation-system/issues/90

**Comment by neilmarion** [comment]
@ssoulless Wow this was a long time ago! Sorry, I wasn't able/wouldn't able to drill down on this problem . :(
