### ISSUE TITLE
Query for 'NOT evaluated by'

### ISSUE THREAD

**Issue by rostaamm** [twitter/activerecord-reputation-system#73]
Hi,
I have two models: User and Question. Users can evaluate Questions (:rating). I'd like to find Mathematics Questions that have NOT been evaluated by a specific user. Something like:

    Question.where(area: "Mathematics).not_evaluated_by(:rating, current_user)

How can I do this?
Thanks.

**Comment by NARKOZ** [comment]
```ruby
evaluated_questions = ReputationSystem::Evaluation.where(target_type: 'Question', source_id: current_user.id, reputation_name: 'rating')

Question.where.not(id: evaluated_questions.pluck(:id))
```
