### ISSUE TITLE
Get only the first 5 evaluators

### ISSUE THREAD

**Issue by thebravoman** [twitter/activerecord-reputation-system#81]
Is it possible to limit the number of evaluators returned.

Something like evalutors_for(:points).limit(5)

And to order the evaluators by its contribution?

**Comment by NARKOZ** [comment]
You can do it like this:

``` ruby
.evaluations.for(:points).includes(:source).order(:created_at).limit(5).map(&:source)
```

That'll be improved in future. Pull requests are welcome.
