### ISSUE TITLE
In the Wiki there is a wrong link

### ISSUE THREAD

**Issue by ssoulless** [twitter/activerecord-reputation-system#88]
Hi here in the wiki: https://github.com/twitter/activerecord-reputation-system/wiki

the link "Asynchronously Process Evaluations" is pointing to "Activate or Deactivate Reputations"

Could you please fix the link? then I can see the contents of "Asynchronously Process Evaluations"

**Comment by NARKOZ** [comment]
Fixed. Thank you.
